# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  static-analysis:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - pmd-v6.41.0
      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.0.1 ]; then
                  curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.41.0/pmd-bin-6.41.0.zip" -o pmd-bin-6.41.0.zip
                  unzip pmd-bin-6.41.0.zip
                  rm pmd-bin-6.41.0.zip
              fi
      - save_cache:
          key: pmd-v6.41.0
          paths:
              - pmd-bin-6.41.0
      - run:
          name: Run Static Analysis
          command: |
              pmd-bin-6.41.0/bin/run.sh pmd -d . -R $RULESET -f text -l apex -r static-analysis.txt
      - store_artifacts:
          path: static-analysis.txt
  build:
    #docker:
    #  - image: cimg/<language>:<version TAG>
    #    auth:
    #      username: mydockerhub-user
    #      password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: exit 0

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 1
  test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - static-analysis
      - build:
          filters:
            branches:
              only: master
          requires:
            - static-analysis
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
          requires: 
            - build